server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-82886997.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaf5ehfe85q1uujF5d7
    client-secret: gp-AMGUA33HXPY1XMacjmNTWvVj7QsNbJNvhHgNaIK68M2RDLDZHpdOtQmcPQHl6
    scopes:
      - openid
      - profile
      - email
      - offline_access