server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KishanUtkarsh/RatingApp-Microservice-Config
          clone-on-start: true